version: '3'
services:
  yet-another-zeno:
    build:
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - PYTHONPATH=/workspace/src/
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1 \
      - PYTHONUTF8=1
      - PYTHONIOENCODING="UTF-8"
      - PYTHONBREAKPOINT="IPython.terminal.debugger.set_trace"
      - PIP_NO_CACHE_DIR=off
      - PIP_DISABLE_PIP_VERSION_CHECK=on
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true