# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\",\n\x0bLocalUpdate\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\x0c\n\x04loss\x18\x02 \x01(\x02\"!\n\x0eServerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\x11\x46\x65\x64\x65ratedLearning\x12\x30\n\x0fSendLocalUpdate\x12\x0c.LocalUpdate\x1a\x0f.ServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCALUPDATE']._serialized_start=19
  _globals['_LOCALUPDATE']._serialized_end=63
  _globals['_SERVERRESPONSE']._serialized_start=65
  _globals['_SERVERRESPONSE']._serialized_end=98
  _globals['_FEDERATEDLEARNING']._serialized_start=100
  _globals['_FEDERATEDLEARNING']._serialized_end=169
# @@protoc_insertion_point(module_scope)
