# number of users: K
num_clients: 20
# the fraction of clients: C
frac: 0.1
# number of faulty workers
num_byzantines: 0
# number of rounds of training
rounds: 20
# number of warmup epochs
warmup_rounds: 5
# type of failures, bitflip or labelflip or chosen-labelflip or gaussian
byzantine_type: "labelflip"
# chosen-labelflip attack, label number of the source
choice_src_label: 5
# chosen-labelflip attack, label number of the destination
choice_dst_label: 3
# aggregation method, "mean", "median", "krum" or "zeno"
aggregation: "mean"
# batch size of Zeno, n_{r} in the paper
zeno_size: 4
# in the paper, r = \frac{\gamma}{\rho}
# ratio to learning late
rho_ratio: 200
# number of trimmed values
num_trimmed_values: 8
# iid: 1 means the workers are training on IID data (Set to 0 for non-IID)
iid: 1
# whether to use unequal data splits for non-i.i.d setting (use 0 for equal splits)
unequal: 0
