# number of users: K
num_clients: 20
# the fraction of clients: C
frac: 1
# number of faulty workers
num_byzantines: 0
# number of rounds of training
rounds: 10
# number of warmup epochs
warmup_rounds: 0
# type of failures, bitflip or labelflip or chosen-labelflip or gaussian
byzantine_type: "labelflip"
# whether enable time-series-monitoring
enable_time_series_monitoring: false
# time_series_convergence (alpha)
time_series_convergence_threshold: 2.0
# time_series_similarity (beta)
time_series_similarity_threshold: 0.85
# whether enable trust-scored clustering
enable_trust_scored_clustering: false
# clustering silhouette score threshold
clustering_silhouette_score_threshold: 0.85
# whether enable time-series-monitoring
enable_cross_sectional_monitoring: false
# chosen-labelflip attack, label number of the source
choice_src_label: 5
# chosen-labelflip attack, label number of the destination
choice_dst_label: 3
# aggregation method, "mean", "median", "krum" or "zeno"
aggregation: "mean"
# # batch size of Zeno, n_{r} in the paper
# zeno_size: 4
# # in the paper, r = \frac{\gamma}{\rho}
# # ratio to learning late
# rho_ratio: 200
# # number of trimmed values
# num_trimmed_values: 8
# IID: `true` means the workers are training on IID data (Set to `false` for Non-IID)
iid: true
# whether to use unequal data splits for non-i.i.d setting (use 0 for equal splits)
unequal: 0
