# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Code Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linter:

    runs-on: ubuntu-latest
    env:
      PYTHONPATH: $GITHUB_WORKSPACE/src/
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort==5.12.0 black==23.7.0 flake8==6.0.0 mypy==1.5.1 pytest==7.4.0 torch==2.0.1
    - name: Format with isort
      run: |
        isort ./src/ ./tests/
    - name: Format with black
      run: |
        black --line-length=79 ./src/ ./tests/
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=79 --ignore=E203,W503 ./src/ ./tests/
    - name: Lint with mypy
      run: |
        mypy --ignore-missing-imports --no-strict-optional ./src ./tests/
    - name: Test with pytest
      run: |
        pytest ./tests/