# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install ruff==0.2.1 mypy==0.971 torch==2.0.1 numpy==1.25.2
      - name: Lint with ruff
        run: |
          python -m ruff check --output-format=github .
      - name: Format with ruff
        run: |
          python -m ruff format . --check --diff
      - name: Lint with mypy
        run: |
          python -m mypy .
